console.log('before loading la and check-more-types')
var la = require('lazy-ass')
var is = require('check-more-types')
console.log('check-more-types version', is.VERSION)
console.log('all finished on Node version', process.version)
