sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  # no tests on CI until we get docker there
  - echo "Tests on Travis require Docker :("
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
